# Generated by Django 4.2.7 on 2025-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
