# Generated by Django 4.2.7 on 2025-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
