# Generated by Django 4.2.7 on 2025-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_no',
            field=models.CharField(default=9841414141, max_length=10),
            preserve_default=False,
        ),
    ]
