# Generated by Django 4.2.7 on 2025-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=77, unique=True),
        ),
    ]
