# Generated by Django 4.2.7 on 2025-08-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0003_remove_account_phone_no_account_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
