# Generated by Django 4.2.7 on 2025-08-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0005_alter_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
