# Generated by Django 4.2.7 on 2025-08-11 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0005_customuser_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='Store_logo')),
                ('store_verification', models.ImageField(blank=True, null=True, upload_to='Store')),
                ('contact_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
