# Generated by Django 4.2.7 on 2025-08-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0006_vendoraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorAccount',
            new_name='StoreAccount',
        ),
    ]
