# Generated by Django 4.2.7 on 2025-08-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grabit_app', '0009_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabit_app.product')),
            ],
        ),
    ]
